In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/Customer_Churn.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.shape

(7043, 21)

In [5]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

In [7]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [8]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df["TotalCharges"].dtype

In [11]:
df["TotalCharges"].isnull().sum()

np.int64(0)

In [12]:
(df["TotalCharges"] == " ").sum()

np.int64(11)

In [13]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [14]:
df["TotalCharges"].dtype

dtype('float64')

In [15]:
df["TotalCharges"].isnull().sum()

np.int64(11)

In [16]:
df["TotalCharges"] = df["TotalCharges"].fillna(df["TotalCharges"].median())

In [17]:
df["TotalCharges"].median()

np.float64(1397.475)

In [18]:
df["TotalCharges"].isnull().sum()

np.int64(0)

In [19]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
dtype: object

In [20]:
df["Contract"].value_counts()

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

In [21]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [23]:
df["Churn"].value_counts(normalize=True)*100

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [24]:
pd.crosstab(df["Contract"], df["Churn"], normalize="index")*100

Churn                  No        Yes
Contract
Month-to-month  57.290323  42.709677
One year        88.730482  11.269518
Two year        97.168142   2.831858

In [25]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7043.000000
mean        0.162147    32.371149       64.761692   2281.916928
std         0.368612    24.559481       30.090047   2265.270398
min         0.000000     0.000000       18.250000     18.800000
25%         0.000000     9.000000       35.500000    402.225000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.850000   3786.600000
max         1.000000    72.000000      118.750000   8684.800000

In [26]:
df["Churn"] = df["Churn"].map({"No": 0, "Yes": 1})

In [27]:
df["Churn"].value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

In [28]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

In [29]:
X.shape

(7043, 20)

In [30]:
y.shape

(7043,)

In [31]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [34]:
X_train.shape, X_test.shape

((5634, 20), (1409, 20))

In [35]:
X.select_dtypes(include="object").columns

C:\Users\pantv\AppData\Local\Temp\ipykernel_20872\2213039483.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X.select_dtypes(include="object").columns

Index(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod'],
      dtype='str')

In [36]:
X = X.drop("customerID", axis=1)

In [37]:
X.shape

(7043, 19)

In [38]:
categorical_features = X.select_dtypes(include=["object", "str"]).columns
numerical_features = X.select_dtypes(exclude=["object", "str"]).columns

In [39]:
print("categorical columns:")
print(categorical_features)

categorical columns:
Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str')

In [40]:
print("\nNumerical columns:")
print(numerical_features)

Numerical columns:
Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')

In [41]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [42]:
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
        ("num", "passthrough", numerical_features)
    ]
)

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [45]:
model = Pipeline(
steps=[
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
]
)

In [46]:
model.fit(X_train, y_train)

c:\Users\pantv\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str')),
                                                 ('num', 'passthrough',
                                                  Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str'))])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [47]:
y_pred = model.predict(X_test)

In [48]:
y_pred

array([0, 1, 0, ..., 0, 0, 0], shape=(1409,))

In [49]:
from sklearn.metrics import accuracy_score

In [50]:
accuracy = accuracy_score(y_test, y_pred)

In [51]:
print("Accuracy:", accuracy)

Accuracy: 0.8048261178140526

In [52]:
from sklearn.metrics import classification_report, confusion_matrix

In [53]:
print("confusion_matrix:")
print(confusion_matrix(y_test, y_pred))

confusion_matrix:
[[925 110]
 [165 209]]

In [54]:
print("\nClassificationn Reports:")
print(classification_report(y_test, y_pred))

Classificationn Reports:
              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1035
           1       0.66      0.56      0.60       374

    accuracy                           0.80      1409
   macro avg       0.75      0.73      0.74      1409
weighted avg       0.80      0.80      0.80      1409

In [55]:
from sklearn.metrics import roc_auc_score

In [56]:
y_probability = model.predict_proba(X_test)[:, 1]
auc = roc_auc_score(y_test, y_probability)
print("ROC_AUC:", auc)

ROC_AUC: 0.8426929137926579

In [57]:
import joblib
joblib.dump(model, "churn_model.pkl")

['churn_model.pkl']

In [59]:
from sklearn.ensemble import RandomForestClassifier

In [60]:
rf_model = Pipeline(
    steps=[
("preprocessor", preprocessor),
("classifier", RandomForestClassifier(
    n_estimators=200,
    random_state=42
))
    ]
)

In [61]:
rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str')),
                                                 ('num', 'passthrough',
                                                  Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str'))])),
                ('classifier',
                 RandomForestClassifier(n_estimators=200, random_state=42))])

In [62]:
rf_pred = rf_model.predict(X_test)

In [63]:
rf_pred

array([0, 1, 0, ..., 0, 0, 0], shape=(1409,))

In [64]:
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

print("Accuracy:", accuracy_score(y_test, rf_pred))

print("\nClassification Report:")
print(classification_report(y_test, rf_pred))

rf_probability = rf_model.predict_proba(X_test)[:, 1]

print("ROC-AUC:", roc_auc_score(y_test, rf_probability))

Accuracy: 0.7806955287437899

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1035
           1       0.61      0.48      0.54       374

    accuracy                           0.78      1409
   macro avg       0.72      0.69      0.70      1409
weighted avg       0.77      0.78      0.77      1409

ROC-AUC: 0.818502157121083

In [65]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import pandas as pd

# Logistic Regression
lr_pred = model.predict(X_test)
lr_prob = model.predict_proba(X_test)[:, 1]

# Random Forest
rf_pred = rf_model.predict(X_test)
rf_prob = rf_model.predict_proba(X_test)[:, 1]

# Comparison
results = pd.DataFrame({
    "Model": ["Logistic Regression", "Random Forest"],
    "Accuracy": [
        accuracy_score(y_test, lr_pred),
        accuracy_score(y_test, rf_pred)
    ],
    "Precision": [
        precision_score(y_test, lr_pred),
        precision_score(y_test, rf_pred)
    ],
    "Recall": [
        recall_score(y_test, lr_pred),
        recall_score(y_test, rf_pred)
    ],
    "F1 Score": [
        f1_score(y_test, lr_pred),
        f1_score(y_test, rf_pred)
    ],
    "ROC-AUC": [
        roc_auc_score(y_test, lr_prob),
        roc_auc_score(y_test, rf_prob)
    ]
})

results

                 Model  Accuracy  Precision    Recall  F1 Score   ROC-AUC
0  Logistic Regression  0.804826   0.655172  0.558824  0.603175  0.842693
1        Random Forest  0.780696   0.610169  0.481283  0.538117  0.818502

In [66]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    "classifier__n_estimators": [100, 200],
    "classifier__max_depth": [5, 10, None],
    "classifier__min_samples_split": [2, 5]
}

grid_search = GridSearchCV(
    rf_model,
    param_grid,
    cv=5,
    scoring="roc_auc",
    n_jobs=-1
)

In [68]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBillin...thod'],
      dtype='str')),
                                                                        ('num',
                                                                         'passthrough',
                                                                         Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str'))])),
                                       ('classifier',
                                        RandomForestClassifier(n_estimators=200,
                                                               random_state=42))]),
             n_jobs=-1,
             param_grid={'classifier__max_depth': [5, 10, None],
                         'classifier__min_samples_split': [2, 5],
                         'classifier__n_estimators': [100, 200]},
             scoring='roc_auc')

In [69]:
print("Best Parameters:")
print(grid_search.best_params_)

print("\nBest ROC_AUC:")
print(grid_search.best_score_)

Best Parameters:
{'classifier__max_depth': 5, 'classifier__min_samples_split': 5, 'classifier__n_estimators': 200}

Best ROC_AUC:
0.8447915104334897

In [70]:
best_rf_model = grid_search.best_estimator_

In [71]:
best_rf_pred =best_rf_model.predict(X_test)

In [72]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

best_rf_prob = best_rf_model.predict_proba(X_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, best_rf_pred))
print("Precision:", precision_score(y_test, best_rf_pred))
print("Recall:", recall_score(y_test, best_rf_pred))
print("F1 Score:", f1_score(y_test, best_rf_pred))
print("ROC-AUC:", roc_auc_score(y_test, best_rf_prob))

print("\nClassification Report:")
print(classification_report(y_test, best_rf_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, best_rf_pred))

Accuracy: 0.7955997161107168
Precision: 0.680672268907563
Recall: 0.43315508021390375
F1 Score: 0.5294117647058824
ROC-AUC: 0.8410757188250795

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.93      0.87      1035
           1       0.68      0.43      0.53       374

    accuracy                           0.80      1409
   macro avg       0.75      0.68      0.70      1409
weighted avg       0.78      0.80      0.78      1409


Confusion Matrix:
[[959  76]
 [212 162]]

In [73]:
import pandas as pd

# Get the trained Random Forest
rf = best_rf_model.named_steps["classifier"]

# Get encoded feature names
feature_names = best_rf_model.named_steps["preprocessor"].get_feature_names_out()

# Create importance table
feature_importance = pd.DataFrame({
    "Feature": feature_names,
    "Importance": rf.feature_importances_
})

# Sort from highest to lowest
feature_importance = feature_importance.sort_values(
    "Importance",
    ascending=False
)

feature_importance.head(15)

                                     Feature  Importance
32              cat__Contract_Month-to-month    0.148168
42                               num__tenure    0.133169
44                         num__TotalCharges    0.096260
14                    cat__OnlineSecurity_No    0.088879
12          cat__InternetService_Fiber optic    0.063903
23                       cat__TechSupport_No    0.063653
34                    cat__Contract_Two year    0.062721
39       cat__PaymentMethod_Electronic check    0.060087
43                       num__MonthlyCharges    0.046271
11                  cat__InternetService_DSL    0.025555
17                      cat__OnlineBackup_No    0.022784
33                    cat__Contract_One year    0.019441
16                   cat__OnlineSecurity_Yes    0.017596
24      cat__TechSupport_No internet service    0.013800
30  cat__StreamingMovies_No internet service    0.012006

In [74]:
import joblib 
joblib.dump(best_rf_model, "churn_model.pkl")
print("Model saved successfully!")

Model saved successfully!

In [75]:
loaded_model = joblib.load("churn_model.pkl")

test_prediction = loaded_model.predict(X_test)

print("Model loaded successfully!")
print("Accuracy:", accuracy_score(y_test, test_prediction))

Model loaded successfully!
Accuracy: 0.7955997161107168

In [76]:
customer = pd.DataFrame({
    "gender": ["Male"],
    "SeniorCitizen": [0],
    "Partner": ["No"],
    "Dependents": ["No"],
    "tenure": [2],
    "PhoneService": ["Yes"],
    "MultipleLines": ["No"],
    "InternetService": ["Fiber optic"],
    "OnlineSecurity": ["No"],
    "OnlineBackup": ["No"],
    "DeviceProtection": ["No"],
    "TechSupport": ["No"],
    "StreamingTV": ["Yes"],
    "StreamingMovies": ["Yes"],
    "Contract": ["Month-to-month"],
    "PaperlessBilling": ["Yes"],
    "PaymentMethod": ["Electronic check"],
    "MonthlyCharges": [85.5],
    "TotalCharges": [171.0]
})

In [77]:
prediction = loaded_model.predict(customer)

probability = loaded_model.predict_proba(customer)[0][1]

print("Prediction:", "Churn" if prediction[0] == 1 else "No Churn")
print("Churn Probability:", round(probability * 100, 2), "%")

Prediction: Churn
Churn Probability: 67.81 %

In [78]:
def predict_churn(customer_data):
    customer = pd.DataFrame([customer_data])

    prediction = loaded_model.predict(customer)[0]
    probability = loaded_model.predict_proba(customer)[0][1]

    result = "Churn" if prediction == 1 else "No Churn"

    return {
        "prediction": result,
        "churn_probability": round(probability * 100, 2)
    }

In [79]:
result = predict_churn({
    "gender": "Male",
    "SeniorCitizen": 0,
    "Partner": "No",
    "Dependents": "No",
    "tenure": 2,
    "PhoneService": "Yes",
    "MultipleLines": "No",
    "InternetService": "Fiber optic",
    "OnlineSecurity": "No",
    "OnlineBackup": "No",
    "DeviceProtection": "No",
    "TechSupport": "No",
    "StreamingTV": "Yes",
    "StreamingMovies": "Yes",
    "Contract": "Month-to-month",
    "PaperlessBilling": "Yes",
    "PaymentMethod": "Electronic check",
    "MonthlyCharges": 85.5,
    "TotalCharges": 171.0
})

print(result)

{'prediction': 'Churn', 'churn_probability': np.float64(67.81)}